/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    AgentBountyBoard: {
      address: "0x25d23b63f166ec74b87b40cbcc5548d29576c56c",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_clawd",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "agentStats",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "completedJobs",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "disputedJobs",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalEarned",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalRating",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approveWork",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "rating",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "cancelJob",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimJob",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "clawd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "disputeWork",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "expireJob",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAgentStats",
          inputs: [
            {
              name: "agent",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "completedJobs",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "disputedJobs",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalEarned",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "avgRating",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCurrentPrice",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getJobAgent",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "agent",
              type: "address",
              internalType: "address",
            },
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "submissionURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "paidAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "rating",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getJobCore",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "poster",
              type: "address",
              internalType: "address",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "minPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "auctionStart",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "auctionDuration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "workDeadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum AgentBountyBoard.JobStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getJobCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "jobs",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "poster",
              type: "address",
              internalType: "address",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "minPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "auctionStart",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "auctionDuration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "workDeadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "agent",
              type: "address",
              internalType: "address",
            },
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "submissionURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "paidAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "rating",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum AgentBountyBoard.JobStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "postJob",
          inputs: [
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "minPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "auctionDuration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "workDeadline",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "submitWork",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "submissionURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "JobCancelled",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobClaimed",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "agent",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "agentId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "paidAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobExpired",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobPosted",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "poster",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "description",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "minPrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxPrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "auctionDuration",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "workDeadline",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkApproved",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "rating",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "paidAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkDisputed",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkSubmitted",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "submissionURI",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41523298,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
